---
- hosts: webserver
  gather_facts: true
  tasks:
    - name: "Get cpu usage"
      shell: "top -b -n 1 | grep %Cpu | awk '{print $2}'"
      register: top
    - name: "Get IP address"
      shell: hostname -i
      register: address
    - debug:
        var: address.stdout
      when: top.stdout >= 02
